#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:mysql://localhost:3306/MUMScheddb?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=yaried
#spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.hibernate.hbm2ddl.import_files=classpath:import.sql
#logging.level.*=OFF

#spring.datasource.url=jdbc:mysql://localhost:3306/userspace
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.hibernate.use-new-id-generator-mappings=false
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql = true







server:port=9090
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true